# Generated by Django 4.0.3 on 2022-04-08 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clock',
            name='clock_out',
            field=models.DateTimeField(null=True),
        ),
    ]
